project:
  type: book
  output-dir: docs
  preview:
    port: 9001
    browser: true

book:
  title: "Investigación reproducible con Quarto y R"
  author:
    - "Felipe Ortega"
    - "María Jesús Algar"
    - "Emilio López Cano"
  date: "2024/10/24"
  chapters:
    - index.qmd
    - part: "Quarto"
      chapters:
        - 01-quarto.qmd
        - 02-doctypes.qmd
        - 03-workflow.qmd
        - 04-singledoc.qmd
    - part: "Libros con Quarto"
      chapters:
        - 05-books.qmd
        - 06-class-notes.qmd
    - part: "Publicaciones"
      chapters:
        - 07-manuscripts.qmd
        - 08-FAIR.qmd
    - 09-add-resources.qmd
    - references.qmd
  appendices:
    - A-command-ref.qmd
    - B-IDEs.qmd
    - C-packages.qmd
    - D-pdf-latex.qmd
    - app-refs.qmd
  downloads: [pdf]

lang: es
bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    include-in-header: 
       text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }



