# Paquetes R y atribuciones

## Requisitos previos {#sec-pkg-requirements}

Para ejecutar los ejemplos incluidos en este taller, se necesita tener instalado
R y una IDE de desarrollo para este lenguaje, como por ejemplo RStudio o Microsoft
VS Code. 

También tenemos que instalar el software [Quarto](https://quarto.org/docs/download/),
que es independiente de R y de la IDE de desarrollo que utilicemos.

Adicionalmente, se necesitan los siguientes paquetes de R:

- `tidyverse`.
- `palmerpenguins`.

Para generar documentos de salida en formato PDF se necesita tener
instalada en el sistema una distribución LaTeX. Quarto ya incluye algunos comandos
para facilitar la instalación de TinyTex, así como para comprobar que este u otro
motor de compilación de LaTeX están disponibles en el sistema.

- [Instalación de TinyTex con Quarto](https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex).
- [Comprobación de herramientas TeX/LaTeX instaladas](https://quarto.org/docs/output-formats/pdf-engine.html#managing-tex).

## Atribución de imágenes e iconos

- [R logo by The R Foundation](https://www.r-project.org/logo/).
- [Python file icons created by Flat Icons - Flaticon](https://www.flaticon.com/free-icons/python-file).
- [Html icons created by Freepik - Flaticon](https://www.flaticon.com/free-icons/html).
- [Microsoft word icons created by Pixel perfect - Flaticon](https://www.flaticon.com/free-icons/microsoft-word).
- [Pdf icons created by Dimitry Miroliubov - Flaticon](https://www.flaticon.com/free-icons/pdf).


